updated train.py
CoEDL/elpis pull request #115
Opened 2020-08-27 07:40 UTC by jinxianghooi

train.py step 4 pronunciation dictionary and dataset linking was outdated and doesn't work. Updated with reference to endpoints code.

2020-09-02 07:55 UTC, nicklambourne requested changes
Can you provide output of this working on the Abui toy corpora?

2020-09-02 07:55 UTC, nicklambourne commented on examples/cli/elan/train.py
> +    ds.importer.set_setting('tier_name', 'tx')
This change is not necessary. Our canonical tests use the Abui toy corpora which uses 'Phrase as the tier name'

2020-09-07 02:23 UTC, benfoley commented on examples/cli/elan/train.py
> +    m.link_pron_dict(pd)
This is fine. Please reset the `tx` change above and I'm happy for this to be merged - it copies the behaviour of the model new endpoint.

2020-09-07 11:16 UTC, benfoley commented
> Can you provide output of this working on the Abui toy corpora?
Jin sent this via Slack
[train.log](https://github.com/CoEDL/elpis/files/5182770/train.log)

2020-09-07 11:16 UTC, merged