Show all logging output on GUI
CoEDL/elpis pull request #220
Opened 2021-06-23 05:17 UTC by mattchrlw

Closes #173. Before it was only showing select info, now it shows the entire output of `train.log`.

![image](https://user-images.githubusercontent.com/36957422/123039738-06108300-d436-11eb-801e-7e358e17caea.png)

2021-06-23 05:22 UTC, nicklambourne approved these changes
LGTM

2021-06-23 10:16 UTC, nicklambourne approved these changes

2021-06-25 00:20 UTC, benfoley requested changes
Please check that both engines have these fixes for consistency.

2021-07-15 07:13 UTC, mattchrlw commented
I've modified the logic a little bit, please have a look now

2021-07-15 07:14 UTC, mattchrlw commented on elpis/engines/kaldi/objects/model.py
> +                    stage_process = run(f"cd {local_kaldi_path}; stages/{stage} &> {stage_log_path}")
`&>` ensures both stderr and stdout are logged as they come. This removes the need to print stdout and stderr to file and then print it out.

2021-07-18 16:22 UTC, nicklambourne approved these changes
LGTM if you can please unstage the yarn changes

2021-07-19 01:22 UTC, benfoley approved these changes

2021-07-19 01:22 UTC, merged