Formatted endpoints
CoEDL/elpis pull request #284
Opened 2022-06-10 01:43 UTC by aviraljain99

Please ignore the change in the dockerfile. I will remove it in the next commit to this PR - it was just for testing. But I have formatted the endpoints directory using black and that is the subject of this PR.

2022-06-10 01:46 UTC, aviraljain99 commented
I was also wondering if any of you had any thoughts on the maximum line length that is enforced by black? The black default is 88 characters.

2022-06-10 01:58 UTC, nicklambourne commented
I'm in favour of 100 char line lengths, 120 at most.

2022-06-10 02:00 UTC, nicklambourne reviewed
Was `black` already in the dependcy closure in pyproject.toml?  What's the process for running black in the repo? Where is the config set?

2022-06-13 05:14 UTC, aviraljain99 commented
@nicklambourne I don't think the black formatter is setup within this repo - neither is it in the pyproject.toml dependency section (is it referred to as a closure?). I will look into it - also sorry for the late response.

2022-06-14 04:44 UTC, harrykeightley commented on .github/workflows/black_python_formatter.yml
> +          DEFAULT_BRANCH: dev
Is this meant to be dev?

2022-06-14 05:45 UTC, aviraljain99 commented
@nicklambourne I have copied over the workflow from elpiscloud that runs the black formatter on the Python files so it should now run that workflow on pushes to master or when there is a PR into master. 

I also added some black configuration info to the pyproject.toml file and set the line length to a 100 characters. Also black is now a dev dependency. Is this PR good to merge into master now?

2022-06-14 07:22 UTC, nicklambourne requested changes
Few nits etc. to address

2022-06-14 07:22 UTC, nicklambourne commented on .github/workflows/black_python_formatter.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Missing newline

2022-06-14 07:22 UTC, nicklambourne commented on .github/workflows/black_python_formatter.yml
> +    runs-on: ubuntu-latest
This should be pinned at a specific version so it doesn't break without warning on us at some undefined point in the future when the definition of what constitutes `latest` changes.

2022-06-14 07:22 UTC, nicklambourne commented on .github/workflows/black_python_formatter.yml
> +    name: Formatter
May want to be more specific, as we'll no doubt have linters for other languages (TS, even HCL)

2022-06-14 07:22 UTC, nicklambourne commented on pyproject.toml
> +target-version = ['py38']
Are we limiting ourselves to py38 for some particular reason?

2022-06-15 01:46 UTC, nicklambourne approved these changes

2022-06-15 01:53 UTC, merged